language: c
os: linux
sudo: false
services:
- xvfb
install:
- wget -O fuck-xuexiqiangguo.zip https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/raw/master/Fuck学习强国-linux.zip
- unzip -q -d ./fuck-xuexiqiangguo/ fuck-xuexiqiangguo.zip
- chmod +x fuck-xuexiqiangguo/Fuck学习强国
script:
- xvfb-run --auto-servernum --server-num=1 fuck-xuexiqiangguo/Fuck学习强国 --headless
1
