language: c
os: linux
sudo: false
dist: bionic
services:
- docker
before_install:
- wget -O Dockerfile https://raw.githubusercontent.com/fuck-xuexiqiangguo/docker/master/Dockerfile
- wget -O script.sh https://raw.githubusercontent.com/fuck-xuexiqiangguo/docker/master/script.sh
- sed -i 's/--headless/--headless --username=$user --passwd=$password --ua="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.3987.132 Safari/537.36"/g' script.sh
- docker build -t fuck-xuexiqiangguo-docker .
- docker run -d --name xuexi fuck-xuexiqiangguo-docker
- docker logs -f xuexi
before_script:
  - curl -l "https://sc.ftqq.com/$sckey.send?text=Start_XueXi~&desp=Build_$TRAVIS_BUILD_NUMBER"
after_success:
  - curl -l "https://sc.ftqq.com/$sckey.send?text=Xuexi_Build_success~&desp=Build_$TRAVIS_BUILD_NUMBER"
after_failure:
  - curl -l "https://sc.ftqq.com/$sckey.send?text=Xuexi_Build_failure~&desp=Build_$TRAVIS_BUILD_NUMBER"
