language: c
os: linux
sudo: false
services:
- docker
before_install:
- wget -O Dockerfile https://raw.githubusercontent.com/fuck-xuexiqiangguo/docker/master/Dockerfile
- wget -O script.sh https://raw.githubusercontent.com/fuck-xuexiqiangguo/docker/master/script.sh
- sed -i "s/--headless/--headless --username=$user --passwd=$password/g" script.sh
- docker build -t fuck-xuexiqiangguo-docker .
- docker run -d --name xuexi fuck-xuexiqiangguo-docker
before_script:
  - curl -l "https://sc.ftqq.com/$sckey.send?text=Start_XueXi~&desp=Build_$TRAVIS_BUILD_NUMBER"
after_success:
  - curl -l "https://sc.ftqq.com/$sckey.send?text=Xuexi_Build_success~&desp=Build_$TRAVIS_BUILD_NUMBER"
after_failure:
  - curl -l "https://sc.ftqq.com/$sckey.send?text=Xuexi_Build_failure~&desp=Build_$TRAVIS_BUILD_NUMBER"
