language: c
os: linux
sudo: false
services:
- xvfb
install:
- wget -O fuck-xuexiqiangguo.zip https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/raw/master/Fuck%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD-linux.zip
- unzip -q -d ./fuck-xuexiqiangguo/ fuck-xuexiqiangguo.zip
- chmod +x fuck-xuexiqiangguo/Fuck%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD
script:
- xvfb-run --auto-servernum --server-num=1 fuck-xuexiqiangguo/Fuck%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD --headless

