language: c
os: linux
sudo: false
dist: bionic
services:
- xvfb
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-zh-hans
install:
- wget -O fuck-xuexiqiangguo.zip https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/raw/master/Fuck%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD-linux.zip
- unzip -q -d ./fuck-xuexiqiangguo/ fuck-xuexiqiangguo.zip
- mv fuck-xuexiqiangguo/Fuck* fuck-xuexiqiangguo/Love
- chmod +x fuck-xuexiqiangguo/Love
before_script:
  - export DISPLAY=:9.0
- Xvfb -ac -screen scrn 1280x2000x24 :9.0 & export DISPLAY=:9.0
  - curl -l "https://sc.ftqq.com/$sckey.send?text=Start_XueXi~&desp=Build_$TRAVIS_BUILD_NUMBER"
after_success:
  - curl -l "https://sc.ftqq.com/$sckey.send?text=Xuexi_Build_success~&desp=Build_$TRAVIS_BUILD_NUMBER"
after_failure:
  - curl -l "https://sc.ftqq.com/$sckey.send?text=Xuexi_Build_failure~&desp=Build_$TRAVIS_BUILD_NUMBER"
script:
- xvfb-run fuck-xuexiqiangguo/Love --headless --ua="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.3987.132 Safari/537.36"
