# This is a basic workflow to help you get started with Actions

name: Auto-Xuexi

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a set of commands using the runners shell
    - name: Installation depends
      run: |
#        sudo apt update
#        sudo apt upgrade
#        sudo apt-get install -y wget unzip libgtk-3-0 xvfb libxss1 libnss3 libasound2
        Xvfb -ac -screen scrn 1280x2000x24 :9.0 & export DISPLAY=:9.0
    - name: Pull and Run
      run: |
        wget -O fuck-xuexiqiangguo.zip https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/raw/master/Fuck学习强国-linux.zip
        unzip -q -d ./fuck-xuexiqiangguo/ fuck-xuexiqiangguo.zip
        cd fuck-xuexiqiangguo
        chmod +x ./Fuck学习强国
        xvfb-run ./Fuck学习强国 --headless --ua="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.3987.132 Safari/537.36"
